### ISSUE TITLE
error in require('cfb.js')

### ISSUE THREAD

**Issue by kingeric027** [CFBD/cfb.js#2]
Hello I am attempting to run your example code from your readme with a node script. However I am unable to import the package because I am getting an error on the first line:
`var cfb = require('cfb.js');`

This is causing the error: Process exited with code 1
and is pointing to line 17 of the index.js file: "Uncaught /Users/ericking/Desktop/myFolder/College Football/jcbJS/node_modules/cfb.js/src/index.js:17"

I was able to install the package successfully with `npm install cfb.js --save`

Looks like a really cool package! Would love to hear back from you. Thanks.

**Comment by BlueSCar** [comment]
This is fixed in package version 4.1.0.
